//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BuildMonitor.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ApplicationDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ApplicationDataEntities object using the connection string found in the 'ApplicationDataEntities' section of the application configuration file.
        /// </summary>
        public ApplicationDataEntities() : base("name=ApplicationDataEntities", "ApplicationDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationDataEntities object.
        /// </summary>
        public ApplicationDataEntities(string connectionString) : base(connectionString, "ApplicationDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationDataEntities object.
        /// </summary>
        public ApplicationDataEntities(EntityConnection connection) : base(connection, "ApplicationDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FeatureSwitch> FeatureSwitches
        {
            get
            {
                if ((_FeatureSwitches == null))
                {
                    _FeatureSwitches = base.CreateObjectSet<FeatureSwitch>("FeatureSwitches");
                }
                return _FeatureSwitches;
            }
        }
        private ObjectSet<FeatureSwitch> _FeatureSwitches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FeatureMessage> FeatureMessages
        {
            get
            {
                if ((_FeatureMessages == null))
                {
                    _FeatureMessages = base.CreateObjectSet<FeatureMessage>("FeatureMessages");
                }
                return _FeatureMessages;
            }
        }
        private ObjectSet<FeatureMessage> _FeatureMessages;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FeatureSwitches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFeatureSwitches(FeatureSwitch featureSwitch)
        {
            base.AddObject("FeatureSwitches", featureSwitch);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FeatureMessages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFeatureMessages(FeatureMessage featureMessage)
        {
            base.AddObject("FeatureMessages", featureMessage);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApplicationDataModel", Name="FeatureMessage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FeatureMessage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FeatureMessage object.
        /// </summary>
        /// <param name="featureMessageId">Initial value of the FeatureMessageId property.</param>
        /// <param name="featureId">Initial value of the FeatureId property.</param>
        public static FeatureMessage CreateFeatureMessage(global::System.Int32 featureMessageId, global::System.Int32 featureId)
        {
            FeatureMessage featureMessage = new FeatureMessage();
            featureMessage.FeatureMessageId = featureMessageId;
            featureMessage.FeatureId = featureId;
            return featureMessage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FeatureMessageId
        {
            get
            {
                return _FeatureMessageId;
            }
            set
            {
                if (_FeatureMessageId != value)
                {
                    OnFeatureMessageIdChanging(value);
                    ReportPropertyChanging("FeatureMessageId");
                    _FeatureMessageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FeatureMessageId");
                    OnFeatureMessageIdChanged();
                }
            }
        }
        private global::System.Int32 _FeatureMessageId;
        partial void OnFeatureMessageIdChanging(global::System.Int32 value);
        partial void OnFeatureMessageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FeatureId
        {
            get
            {
                return _FeatureId;
            }
            set
            {
                OnFeatureIdChanging(value);
                ReportPropertyChanging("FeatureId");
                _FeatureId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FeatureId");
                OnFeatureIdChanged();
            }
        }
        private global::System.Int32 _FeatureId;
        partial void OnFeatureIdChanging(global::System.Int32 value);
        partial void OnFeatureIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApplicationDataModel", Name="FeatureSwitch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FeatureSwitch : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FeatureSwitch object.
        /// </summary>
        /// <param name="featureName">Initial value of the FeatureName property.</param>
        /// <param name="featureSwitchId">Initial value of the FeatureSwitchId property.</param>
        /// <param name="enabled">Initial value of the Enabled property.</param>
        public static FeatureSwitch CreateFeatureSwitch(global::System.String featureName, global::System.Int32 featureSwitchId, global::System.Boolean enabled)
        {
            FeatureSwitch featureSwitch = new FeatureSwitch();
            featureSwitch.FeatureName = featureName;
            featureSwitch.FeatureSwitchId = featureSwitchId;
            featureSwitch.Enabled = enabled;
            return featureSwitch;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FeatureName
        {
            get
            {
                return _FeatureName;
            }
            set
            {
                OnFeatureNameChanging(value);
                ReportPropertyChanging("FeatureName");
                _FeatureName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FeatureName");
                OnFeatureNameChanged();
            }
        }
        private global::System.String _FeatureName;
        partial void OnFeatureNameChanging(global::System.String value);
        partial void OnFeatureNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FeatureSwitchId
        {
            get
            {
                return _FeatureSwitchId;
            }
            set
            {
                if (_FeatureSwitchId != value)
                {
                    OnFeatureSwitchIdChanging(value);
                    ReportPropertyChanging("FeatureSwitchId");
                    _FeatureSwitchId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FeatureSwitchId");
                    OnFeatureSwitchIdChanged();
                }
            }
        }
        private global::System.Int32 _FeatureSwitchId;
        partial void OnFeatureSwitchIdChanging(global::System.Int32 value);
        partial void OnFeatureSwitchIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Enabled
        {
            get
            {
                return _Enabled;
            }
            set
            {
                OnEnabledChanging(value);
                ReportPropertyChanging("Enabled");
                _Enabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Enabled");
                OnEnabledChanged();
            }
        }
        private global::System.Boolean _Enabled;
        partial void OnEnabledChanging(global::System.Boolean value);
        partial void OnEnabledChanged();

        #endregion

    
    }

    #endregion

    
}
